Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PR4.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/PrestamoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Data.Entity;

namespace PR4.Controllers
{
    public class PrestamoController : Controller
    {
        // GET: Prestamo
        #region Contexto


        private practica4Entities _contexto;

        public practica4Entities contexto
        {
            set { _contexto = value; }
            get
            {
                if (_contexto == null)
                    _contexto = new practica4Entities();
                return _contexto;
            }
        }
        #endregion

        public ActionResult Index()
        {
            
            return View(contexto.prestamos.ToList());
      
        }

        public ActionResult Create()
        {
            //Generar ID automático
            Random rd = new Random();
            int rand_num = rd.Next(1001, 1999);
            ViewBag.id_generado = rand_num;

            //Lista de Libros
            List<libro> libros = contexto.libro.ToList();
            ViewBag.listaLibros = contexto.libro.ToList();

            //Lista de Usuarios
            List<usuario> usuarios = contexto.usuario.ToList();
            ViewBag.listaUsuarios = contexto.usuario.ToList();

            return View();

        }

        [HttpPost]
        public ActionResult Create(prestamos nuevoPrestamo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    contexto.prestamos.Add(nuevoPrestamo);
                    contexto.SaveChanges();

                    return RedirectToAction("Index");
                }
                return View(nuevoPrestamo);
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            prestamos categoriaEditar = contexto.prestamos.Find(id);

            if (categoriaEditar == null)
                return HttpNotFound();


            return View(categoriaEditar);
        }

        [HttpPost]
        public ActionResult Edit(prestamos PrestamoEditar)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    contexto.Entry(PrestamoEditar).State = EntityState.Modified;
                    contexto.SaveChanges();

                    return RedirectToAction("Index");
                }
                return View(PrestamoEditar);
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

           prestamos prestamoEliminar = contexto.prestamos.Find(id);

            if (prestamoEliminar == null)
                return HttpNotFound();

            return View(prestamoEliminar);
        }

        [HttpPost]
        public ActionResult Delete(int? id, prestamos Categoria1)
        {
            try
            {
                prestamos prestamoEliminar = new prestamos();
                if (ModelState.IsValid)
                {
                    if (id == null)
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                    prestamoEliminar = contexto.prestamos.Find(id);

                    if (prestamoEliminar == null)
                        return HttpNotFound();

                    contexto.prestamos.Remove(prestamoEliminar);
                    contexto.SaveChanges();

                    return RedirectToAction("Index");
                }
                return View(prestamoEliminar);
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            //var autorPorPrestamo = from p in contexto.libro
            //                            orderby p.IdLibro ascending
            //                            where p.IdLibro == id
            //                            select p;
            //return View(autorPorPrestamo.ToList());
           

            var libroPorPrestamo = from p in contexto.libro
                                   orderby p.IdLibro ascending
                                   where p.IdLibro == id
                                   select p;
            return View(libroPorPrestamo.ToList());
        }

    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Prestamo/Create.cshtml
@model prestamos
@{
    ViewBag.Title = "Create";
}
<nav style="background-color: #21BF73; border-radius: 20px; margin-bottom:10px;" class="navbar navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand fw-bolder">&nbsp;&nbsp;&nbsp;Create</a>
        <form class="d-flex">
            @Html.ActionLink("Retornar al Index", "Index", null, new { @class = "btn btn-warning col-auto" })
        </form>
    </div>
</nav>


        <div class="container">
            <div class="row">
                <div class="col">
                    <div style="padding:20px; width:600px;">

                        @*<div class="input-group mb-3">
            <span class="input-group-text fw-bold" id="basic-addon1">@Html.LabelFor(model => model.IdPrestamo, new { @class = "form-label" })</span>
            @Html.EditorFor(model => model.IdPrestamo, new { @class = "form-control", @Value   = ViewBag.id_generado, htmlAttributes = new { @Value = ViewBag.id_generado, disabled = true } })
            @Html.ValidationMessageFor(model => model.IdPrestamo)
        </div>*@@using (Html.BeginForm())
                        {
                            @Html.ValidationSummary(true)

                            <div class="input-group mb-3">
                                <span class="input-group-text fw-bold" id="basic-addon1">@Html.LabelFor(model => model.IdPrestamo, new { @class = "form-label" })</span>
                                @Html.EditorFor(model => model.IdPrestamo, new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.id_generado } })
                                @Html.ValidationMessageFor(model => model.IdPrestamo)
                            </div>
                            <div class="input-group mb-3">
                                <span class="input-group-text fw-bold" id="basic-addon1">@Html.LabelFor(model => model.IdLibro, new { @class = "form-label" })</span>
                                @Html.EditorFor(model => model.IdLibro, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.IdLibro)
                            </div>
                            <div class="input-group mb-3">
                                <span class="input-group-text fw-bold" id="basic-addon1">@Html.LabelFor(model => model.IdUsuario, new { @class = "form-label" })</span>
                                @Html.EditorFor(model => model.IdUsuario, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.IdUsuario)
                            </div>
                            <div class="input-group mb-3">
                                <span class="input-group-text fw-bold" id="basic-addon1">@Html.LabelFor(model => model.FecPrestamo, new { @class = "form-label" })</span>
                                @Html.EditorFor(model => model.FecPrestamo, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.FecPrestamo)
                            </div>
                            <div class="input-group mb-3">
                                <span class="input-group-text fw-bold" id="basic-addon1">@Html.LabelFor(model => model.FecDevolucion, new { @class = "form-label" })</span>
                                @Html.EditorFor(model => model.FecDevolucion, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.FecDevolucion)
                            </div>

                            <div class="">
                                <input type="submit" class="btn btn-primary " value="Create" />
                            </div>


                        }

                    </div>



                </div>
                <div class="col">
                    
                    <nav style="background-color: #21BF73; border-radius: 20px; margin-bottom:10px;" class="navbar navbar-dark">
                        <div class="container-fluid">
                            <a class="navbar-brand fw-bolder">&nbsp;&nbsp;&nbsp;Lista de Libros</a>

                        </div>
                    </nav>
                    <div class="table-responsive">
                        <table id="tblLista" class="table table-bordered border-success">
                            <thead class="table-success">
                                <tr>
                                    <th scope="col">IdLibro</th>
                                    <th scope="col">IdAutor</th>
                                    <th scope="col">Codigo</th>
                                    <th scope="col">ISBN</th>
                                    <th scope="col">Titulo</th>
                                    <th scope="col">Editorial</th>
                                    <th scope="col">NumPags</th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var libro in ViewBag.listaLibros)
                                {
                                    <tr>
                                        <th>@libro.IdLibro</th>
                                        <td>@libro.IdAutor</td>
                                        <td>@libro.Codigo</td>
                                        <td>@libro.Titulo</td>
                                        <th>@libro.ISBN</th>
                                        <td>@libro.Editorial</td>
                                        <td>@libro.NumPags</td>

                                    </tr>
                                }
                            </tbody>
                        </table>

                        <nav style="background-color: #21BF73; border-radius: 20px; margin-bottom:10px;" class="navbar navbar-dark">
                            <div class="container-fluid">
                                <a class="navbar-brand fw-bolder">&nbsp;&nbsp;&nbsp;Lista de Usuarios</a>
                                
                            </div>
                        </nav>
                        <div class="table-responsive">
                            <table id="tblLista" class="table table-bordered border-success">
                                <thead class="table-success">
                                    <tr>
                                        <th scope="col">IdUsuario</th>
                                        <th scope="col">NumUsuario</th>
                                        <th scope="col">NIF</th>
                                        <th scope="col">Nombre</th>
                                        <th scope="col">Direccion</th>
                                        <th scope="col">Telefono</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var user in  ViewBag.listaUsuarios)
                                    {
                                    <tr>
                                        <th>@user.IdUsuario</th>
                                        <td>@user.NumUsuario</td>
                                        <td>@user.NIF</td>
                                        <td>@user.Nombre</td>
                                        <td>@user.Direccion</td>
                                        <td>@user.Telefono</td>
                                        
                                    </tr>
                                    }
                                </tbody>
                            </table>

                        </div>

                    </div>
        </div>

Views/Prestamo/Delete.cshtml
@model prestamos

@{
    ViewBag.Title = "Delete";
}

<nav style="background-color: #21BF73; border-radius: 20px; margin-bottom:10px;" class="navbar navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand fw-bolder">&nbsp;&nbsp;&nbsp;Create</a>
        <form class="d-flex">
            @Html.ActionLink("Retornar al Index", "Index", null, new { @class = "btn btn-warning col-auto" })
        </form>
    </div>
</nav>

<div style="padding:20px; width:600px;">

    <div class="input-group mb-3">
        <span class="input-group-text fw-bold" id="basic-addon1">@Html.LabelFor(model => model.IdPrestamo, new { @class = "form-label" })</span>
        @Html.EditorFor(model => model.IdPrestamo, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.IdPrestamo)
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text fw-bold" id="basic-addon1">@Html.LabelFor(model => model.IdLibro, new { @class = "form-label" })</span>
        @Html.EditorFor(model => model.IdLibro, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.IdLibro)
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text fw-bold" id="basic-addon1">@Html.LabelFor(model => model.IdLibro, new { @class = "form-label" })</span>
        @Html.EditorFor(model => model.IdUsuario, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.IdUsuario)
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text fw-bold" id="basic-addon1">@Html.LabelFor(model => model.FecPrestamo, new { @class = "form-label" })</span>
        @Html.EditorFor(model => model.FecPrestamo, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.FecPrestamo)
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text fw-bold" id="basic-addon1">@Html.LabelFor(model => model.FecDevolucion, new { @class = "form-label" })</span>
        @Html.EditorFor(model => model.FecDevolucion, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.FecDevolucion)
    </div>

    @using (Html.BeginForm())
    {
        <div class="col-auto">
            <input type="submit" class="btn btn-danger" value="Delete" />
        </div>
    }
</div>

Views/Prestamo/Details.cshtml
@model IEnumerable<PR4.libro>
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<nav style="background-color: #21BF73; border-radius: 20px; margin-bottom:10px;" class="navbar navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand fw-bolder">&nbsp;&nbsp;&nbsp;Detalles del Préstamo</a>
        <form class="d-flex">
            @Html.ActionLink("Retornar al Index", "Index", null, new { @class = "btn btn-warning col-auto" })
            &nbsp;&nbsp;&nbsp;
            @Html.ActionLink("Nuevo Prestamo", "Create", null, new { @class = "btn btn-primary col-auto" })
        </form>
    </div>
</nav>


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header fw-bolder">
                Libro Prestado a @ViewBag.user
            </div>

            <div class="card-body">

                <div class="table-responsive">
                    <table id="tblLista" class="table table-bordered border-success">
                        <thead class="table-success">
                            <tr>
                                <th scope="col">@Html.DisplayNameFor(model => model.IdLibro)</th>
                                <th scope="col">@Html.DisplayNameFor(model => model.Codigo)</th>
                                <th scope="col">@Html.DisplayNameFor(model => model.ISBN)</th>
                                <th scope="col">@Html.DisplayNameFor(model => model.Titulo)</th>
                                <th scope="col">@Html.DisplayNameFor(model => model.Editorial)</th>
                                <th scope="col">@Html.DisplayNameFor(model => model.NumPags)</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var product in Model)
                            {
                                <tr>
                                    <th>@Html.DisplayFor(modelItem => product.IdLibro)</th>
                                    <td>@Html.DisplayFor(modelItem => product.Codigo)</td>
                                    <td>@Html.DisplayFor(modelItem => product.ISBN)</td>
                                    <td>@Html.DisplayFor(modelItem => product.Titulo)</td>
                                    <td>@Html.DisplayFor(modelItem => product.Editorial)</td>
                                    <td>@Html.DisplayFor(modelItem => product.NumPags)</td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>

            </div>

        </div>
    </div>
</div>

Views/Prestamo/Edit.cshtml
@model prestamos
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
@using (Html.BeginForm())
{
    <div class="input-group mb-3">
        <span class="input-group-text fw-bold" id="basic-addon1">@Html.LabelFor(model => model.IdPrestamo, new { @class = "form-label" })</span>
        @Html.EditorFor(model => model.IdPrestamo, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.IdPrestamo)
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text fw-bold" id="basic-addon1">@Html.LabelFor(model => model.IdLibro, new { @class = "form-label" })</span>
        @Html.EditorFor(model => model.IdLibro, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.IdLibro)
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text fw-bold" id="basic-addon1">@Html.LabelFor(model => model.IdLibro, new { @class = "form-label" })</span>
        @Html.EditorFor(model => model.IdUsuario, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.IdUsuario)
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text fw-bold" id="basic-addon1">@Html.LabelFor(model => model.FecPrestamo, new { @class = "form-label" })</span>
        @Html.EditorFor(model => model.FecPrestamo, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.FecPrestamo)
    </div>
    <div class="input-group mb-3">
        <span class="input-group-text fw-bold" id="basic-addon1">@Html.LabelFor(model => model.FecDevolucion, new { @class = "form-label" })</span>
        @Html.EditorFor(model => model.FecDevolucion, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.FecDevolucion)
    </div>

    <div class="col-auto">
        <input type="submit" class="btn btn-primary mb-3" value="Save" />
    </div>

}

<div>
    @Html.ActionLink("Retornar al Index", "Index")
</div>

Views/Prestamo/Index.cshtml
@model IEnumerable<PR4.prestamos>
@{
    ViewBag.Title = "Index";
}

<nav style="background-color: #21BF73; border-radius: 20px; margin-bottom:10px;" class="navbar navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand fw-bolder">&nbsp;&nbsp;&nbsp;Index</a>
        <form class="d-flex">
            @Html.ActionLink("Nuevo Préstamo", "Create", null, new { @class = "btn btn-warning" })
        </form>
    </div>
</nav>

<table class="table table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdPrestamo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdLibro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdUsuario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FecPrestamo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FecDevolucion)
        </th>
        <th>
            Accciones
        </th>
    </tr>
    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.IdPrestamo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.IdLibro)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.IdUsuario)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FecPrestamo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FecDevolucion)
    </td>
    <td>
        @Html.ActionLink("Editar", "Edit", new { id = item.IdPrestamo }, new { @class = "btn btn-primary" })
        @Html.ActionLink("Detalles", "Details", new { id = item.IdLibro }, new { @class = "btn btn-secondary" })
        @Html.ActionLink("Borrar", "Delete", new { id = item.IdPrestamo }, new { @class = "btn btn-danger" })
    </td>
</tr>
    }

</table>

Views/Shared/DisplayTemplates/DateTime.cshtml
@model Nullable<DateTime>
@(Model != null ? string.Format("{0:d}", Model) : string.Empty)

Views/Shared/EditorTemplates/DateTime.cshtml
@model Nullable<DateTime>

@{
    DateTime dt = DateTime.Now;
    if (Model != null)
    {
        dt = (System.DateTime)Model;

    }
    @Html.TextBox("", String.Format("{0:d}", dt.ToShortDateString()),
     new { @class = "datefield", type = "string" })
}

Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>@ViewBag.Title - My ASP.NET Application</title>
   
    @Styles.Render("~/Content/jquery-ui.css")
</head>
<body style="background-color: #F3F0D7;">
    @*Navbar*@

    <nav style="background-color: #396EB0;" class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <a href="#" class="navbar-brand">
                <img src="https://th.bing.com/th/id/R.24cca5aa0c8beb046d8e04b2a39e1857?rik=MAc52lHUiCf22w&pid=ImgRaw&r=0" height="28" alt="CoolBrand">
            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ">
                    @Html.ActionLink("Biblioteca Ricardo Palma", "Index", "Home", new { area = "" }, new { @class = "navbar-brand nav-item nav-link fw-bolder text-white" })
                    @Html.ActionLink("Préstamos", "Index", "Prestamo", new { area = "" }, new { @class = "nav-item nav-link fw-bold text-white" })
                    @Html.ActionLink("Nuevo Préstamo", "Create", "Prestamo", new { area = "" }, new { @class = "nav-item nav-link fw-bold text-white" })

                </div>
            </div>
        </div>
    </nav>


    @*Render Body*@
    <div>
        <div style="padding-top:20px" class="container">
            <div class="card">
                <div class="card-body">
                    @RenderBody()
                </div>
            </div>

            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/jquery-ui.js")
    @Scripts.Render("~/Scripts/DatePickerReady.js")
</body>
</html>